version: '3'
services:
  nagios:    
    env_file: .env
    image: jasonrivers/nagios:latest
    container_name: ${APP_CONTAINER_NAME}
    environment:
      - TZ=America/Fortaleza
    volumes:
      - ./nagios/nagiosetc:/opt/nagios/etc
      - ./nagios/nagiosvar:/opt/nagios/var
      - ./nagios/customplugins:/opt/Custom-Nagios-Plugins
      - ./nagios/nagiosgraphvar:/opt/nagiosgraph/var
      - ./nagios/nagiosgraphetc:/opt/nagiosgraph/etc
    ports:
      - ${APP_PORT}:80
    networks:      
      rede:
        ipv4_address: 172.33.0.2

networks:
  rede:
    ipam:
      driver: default
      config:
        - subnet: 172.33.0.0/24